embedding_size: 64
layer: 2
learning_rate: 0.0005
node_dropout_rate: 0.1
mess_dropout_rate: 0.1
weight_decay: 5e-5
cos_loss: 1
user_loss: 1e-08
item_loss: 1e-07
train_neg_sample_args: {'sample_num':10}
stopping_step: 20
benchmark_filename: ['train','valid','test']
