embedding_size: 64
layer: 2
train_neg_sample_args: {'sample_num':1}
learning_rate: 0.01
benchmark_filename: ['train','valid','test']
mess_dropout_rate: 0.0
weight_decay: 1e-5
cos_loss: 1
user_loss: 1e-05
item_loss: 1e-07
stopping_step: 20
